from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView
from .views import PreregistroCreateView, MiPerfilView, PerfilAspiranteView, PanelAdministradorView, PanelCoordinacionView, EstadoAspiranteCoordinacionView, AspiranteCoordinacionDetailView, SolicitarApoyoView, InicioSesionView, DocumentoAspiranteView, DocumentoDescargaView, SeguimientoAspiranteView, MarcarNotificacionesLeidasView, EvaluacionColegioView, MisMateriasDisponiblesView, MisInscripcionesView, SolicitudAcademicaView, MisEntrevistasView, MisExamenesView, HorarioDescargaView, HorarioFormalDescargaView, ReinscripcionDescargaView, BoletaInscripcionView, MateriasListView, CursosUploadView, GenerarCargaView, CalificacionesDownloadView, AdscripcionDownloadView, DarBajaView, ConvertirAlumnoView, ConvertirMismaCuentaView
from .docente_views import PanelDocenteView, DocenteCatalogoMateriasView, DocenteMateriaView, CalificacionesView, ActasCalificacionesView, DocenteExamenView, DocenteExamenDetailView, DocenteEntrevistaView, DocenteEntrevistaDetailView
from .views import ExpedienteDigitalView, FirmaElectronicaView, CargaAcademicaWorkflowView, PeriodoInscripcionView, CoordinacionReporteView
from .servicios_views import ServiciosEscolaresPanelView, ServiciosEscolaresAlumnoView, ServiciosEscolaresValidacionView, ServiciosEscolaresReporteView, ServiciosEscolaresDocumentoView
from .admin_views import AdminUsuariosView, AdminUsuarioDetailView, AdminCatalogosView, AdminAlumnosView, AdminDocentesView, AdminReportesView, AdminAuditoriaView, AdminConfiguracionView
from .director_views import DirectorPanelView

urlpatterns = [
    path('servicios-escolares/panel/', ServiciosEscolaresPanelView.as_view(), name='servicios-panel'),
    path('servicios-escolares/alumnos/<int:pk>/', ServiciosEscolaresAlumnoView.as_view(), name='servicios-alumno'),
    path('servicios-escolares/alumnos/<int:pk>/validar-inscripcion/', ServiciosEscolaresValidacionView.as_view(), name='servicios-validar-inscripcion'),
    path('servicios-escolares/reportes/', ServiciosEscolaresReporteView.as_view(), name='servicios-reportes'),
    path('servicios-escolares/alumnos/<int:pk>/documentos/<str:tipo>/', ServiciosEscolaresDocumentoView.as_view(), name='servicios-documento'),
    path('servicios-escolares/expedientes/', ExpedienteDigitalView.as_view(), name='expedientes-digitales'),
    path('servicios-escolares/expedientes/<int:pk>/', ExpedienteDigitalView.as_view(), name='expediente-digital-detail'),
    path('expedientes/<int:pk>/firma/', FirmaElectronicaView.as_view(), name='firma-electronica'),
    path('cargas-academicas/', CargaAcademicaWorkflowView.as_view(), name='cargas-academicas'),
    path('cargas-academicas/<int:pk>/', CargaAcademicaWorkflowView.as_view(), name='carga-academica-detail'),
    path('periodos-inscripcion/', PeriodoInscripcionView.as_view(), name='periodos-inscripcion'),
    path('preregistro/',    PreregistroCreateView.as_view(), name='preregistro-create'),
    path('preregistro/me/', MiPerfilView.as_view(),          name='preregistro-me'),
    path('preregistro/perfil/', PerfilAspiranteView.as_view(), name='perfil-aspirante'),
    path('preregistro/seguimiento/', SeguimientoAspiranteView.as_view(), name='seguimiento-aspirante'),
    path('preregistro/documentos/', DocumentoAspiranteView.as_view(), name='documentos-aspirante'),
    path('preregistro/documentos/<int:pk>/', DocumentoAspiranteView.as_view(), name='documento-aspirante'),
    path('preregistro/documentos/<int:pk>/descarga/', DocumentoDescargaView.as_view(), name='documento-descarga'),
    path('administracion/panel/', PanelAdministradorView.as_view(), name='admin-panel'),
    path('administracion/aspirantes/<int:pk>/', PanelAdministradorView.as_view(), name='admin-aspirante-detail'),
    path('administracion/usuarios/', AdminUsuariosView.as_view(), name='admin-usuarios'),
    path('administracion/usuarios/<int:pk>/', AdminUsuarioDetailView.as_view(), name='admin-usuario-detail'),
    path('administracion/catalogos/', AdminCatalogosView.as_view(), name='admin-catalogos'),
    path('administracion/alumnos/', AdminAlumnosView.as_view(), name='admin-alumnos'),
    path('administracion/alumnos/<int:pk>/', AdminAlumnosView.as_view(), name='admin-alumno-detail'),
    path('administracion/docentes/', AdminDocentesView.as_view(), name='admin-docentes'),
    path('administracion/reportes/', AdminReportesView.as_view(), name='admin-reportes'),
    path('administracion/auditoria/', AdminAuditoriaView.as_view(), name='admin-auditoria'),
    path('administracion/configuracion/', AdminConfiguracionView.as_view(), name='admin-configuracion'),
    path('coordinacion/panel/', PanelCoordinacionView.as_view(), name='coordinacion-panel'),
    path('coordinacion/aspirantes/<int:pk>/estado/', EstadoAspiranteCoordinacionView.as_view(), name='coordinacion-estado-aspirante'),
    path('coordinacion/aspirantes/<int:pk>/', AspiranteCoordinacionDetailView.as_view(), name='coordinacion-aspirante-detail'),
    path('coordinacion/materias/',                MateriasListView.as_view(), name='coordinacion-materias'),
    path('coordinacion/cursos/upload/',           CursosUploadView.as_view(), name='coordinacion-cursos-upload'),
    path('coordinacion/cargas/generar/',          GenerarCargaView.as_view(), name='coordinacion-cargas-generar'),
    path('coordinacion/reportes/',               CoordinacionReporteView.as_view(), name='coordinacion-reportes'),
    path('coordinacion/aspirantes/<int:pk>/calificaciones/', CalificacionesDownloadView.as_view(), name='coordinacion-calificaciones'),
    path('coordinacion/aspirantes/<int:pk>/adscripcion/download/', AdscripcionDownloadView.as_view(), name='coordinacion-adscripcion-download'),
    path('coordinacion/aspirantes/<int:pk>/dar_baja/', DarBajaView.as_view(), name='coordinacion-dar-baja'),
    path('coordinacion/aspirantes/<int:pk>/convertir/',           ConvertirAlumnoView.as_view(), name='coordinacion-convertir-alumno'),
    path('docente/panel/', PanelDocenteView.as_view(), name='docente-panel'),
    path('docente/catalogo-materias/', DocenteCatalogoMateriasView.as_view(), name='docente-catalogo-materias'),
    path('docente/catalogo-materias/<int:pk>/', DocenteCatalogoMateriasView.as_view(), name='docente-seleccionar-materia'),
    path('docente/materias/<int:pk>/', DocenteMateriaView.as_view(), name='docente-materia'),
    path('docente/calificaciones/', CalificacionesView.as_view(), name='docente-calificaciones'),
    path('docente/calificaciones/<int:pk>/', CalificacionesView.as_view(), name='docente-calificacion-update'),
    path('docente/actas/<int:materia_id>/', ActasCalificacionesView.as_view(), name='docente-actas'),
    path('docente/examenes/', DocenteExamenView.as_view(), name='docente-examenes'),
    path('docente/examenes/<int:pk>/', DocenteExamenDetailView.as_view(), name='docente-examen-detail'),
    path('docente/entrevistas/', DocenteEntrevistaView.as_view(), name='docente-entrevistas'),
    path('docente/entrevistas/<int:pk>/', DocenteEntrevistaDetailView.as_view(), name='docente-entrevista-detail'),
    path('director/panel/', DirectorPanelView.as_view(), name='director-panel'),
    path('preregistro/entrevistas/', MisEntrevistasView.as_view(), name='mis-entrevistas'),
    path('preregistro/examenes/', MisExamenesView.as_view(), name='mis-examenes'),
    path('preregistro/evaluaciones-colegio/', EvaluacionColegioView.as_view(), name='evaluaciones-colegio'),
    path('preregistro/evaluaciones-colegio/<int:pk>/', EvaluacionColegioView.as_view(), name='evaluacion-colegio-detail'),
    path('preregistro/apoyo/solicitar/', SolicitarApoyoView.as_view(), name='solicitar-apoyo'),
    path('preregistro/notificaciones/marcar-leidas/', MarcarNotificacionesLeidasView.as_view(), name='marcar-notificaciones-leidas'),
    path('preregistro/convertir-misma-cuenta/', ConvertirMismaCuentaView.as_view(), name='convertir-misma-cuenta'),
    path('preregistro/materias/', MisMateriasDisponiblesView.as_view(), name='materias-disponibles'),
    path('preregistro/inscripciones/', MisInscripcionesView.as_view(), name='mis-inscripciones'),
    path('preregistro/solicitudes-academicas/', SolicitudAcademicaView.as_view(), name='solicitudes-academicas'),
    path('preregistro/horario/download/', HorarioFormalDescargaView.as_view(), name='horario-descarga'),
    path('preregistro/reinscripcion/download/', BoletaInscripcionView.as_view(), name='reinscripcion-descarga'),
    path('preregistro/boleta-inscripcion/download/', BoletaInscripcionView.as_view(), name='boleta-inscripcion-descarga'),
    path('auth/login/',     InicioSesionView.as_view(),       name='token-obtain'),
    path('auth/refresh/',   TokenRefreshView.as_view(),      name='token-refresh'),
]
