import {useLanguage} from '../translations';

const copy = {
  es: {
    locale:'es-MX', panelTitle:'Panel del Aspirante', loading:'Cargando...', requestFallback:'Tu solicitud', loadingRequest:'Cargando información de tu solicitud...', retry:'Reintentar', sidebarTitle:'Secciones', sidebarHint:'Abre cada apartado para ver su contenido.', logout:'Cerrar sesión', notifications:'Notificaciones',
    menu:{perfil:'Mi perfil', inicio:'Inicio', expediente:'Expediente', proceso:'Seguimiento LIDA', documentos:'Documentos', examenes:'Exámenes en línea'},
    stages:{pendiente:'Pre-registro recibido', iniciado:'Proceso iniciado', revision:'En revisión', aceptado:'Aceptado', rechazado:'No aceptado', baja:'Baja'},
    stageMessages:{pendiente:'Tu pre-registro fue recibido. La Coordinación Académica lo revisará pronto.', iniciado:'El flujo LIDA fue iniciado. Pronto estará en revisión.', revision:'Tu expediente está siendo revisado por la Coordinación Académica.', aceptado:'¡Felicidades! Tu solicitud fue aceptada.', rechazado:'Tu solicitud no fue aceptada. Consulta las observaciones o comunícate con Coordinación Académica.', baja:'Tu registro fue dado de baja. Comunícate con Coordinación Académica para solicitar información.'},
    messages:{sessionExpired:'Tu sesión ha caducado. Vuelve a iniciar sesión para continuar.', profileLoadError:'No se pudo cargar tu perfil. Verifica la conexión e inténtalo de nuevo.', trackingError:'No se pudo cargar el seguimiento.', conversionDeclined:'Si deseas solicitar apoyo más adelante, puedes hacerlo una vez más.', conversionSuccess:'Tu cuenta quedó activa como alumno. Inicia sesión nuevamente para entrar al panel de alumno con tus mismas credenciales.', conversionLogout:'Tu cuenta fue convertida a alumno. Inicia sesión nuevamente para continuar.', conversionError:'No se pudo completar la transición.', noNotifications:'No hay notificaciones recientes.', loadingNotifications:'Cargando notificaciones...', noExams:'Aún no tienes exámenes asignados.', noRecord:'No hay expediente digital disponible.', integratingRecord:'Integrando expediente digital...', noEvents:'Aún no hay movimientos registrados.'},
    conversion:{aria:'Confirmación de transición', title:'Continuar como alumno', question:'¿Deseas convertir tu cuenta a alumno ahora y entrar al panel correspondiente con tus mismas credenciales?', cancel:'No, recordar después', confirm:'Sí, continuar', processing:'Procesando...'},
    overview:{summary:'Resumen de tu solicitud', currentStage:'Etapa actual', currentModality:'Modalidad', currentUnit:'Unidad', low:'Registro dado de baja', rejected:'Solicitud no aceptada', quick:'Acceso rápido', fullRecord:'Ver expediente completo', track:'Ver proceso LIDA', continueStudent:'Continuar como alumno', next:'Próximo paso', stage:'Etapa actual', recentNotifications:'Notificaciones recientes', update:'Actualizar', centralRecord:'EXPEDIENTE ESTUDIANTIL CENTRALIZADO', thesis:'Trayectoria de tesis', defense:'Defensa', signatures:'Firmas electrónicas', personal:'Datos personales', addresses:'Domicilios', current:'Actual', permanent:'Permanente', education:'Escolaridad', affiliation:'Adscripción', documents:'Documentos', enrollments:'Inscripciones', requests:'Solicitudes', signaturesCount:'Firmas', thesisProjects:'Proyectos de tesis', movements:'Movimientos', name:'Nombre', curp:'CURP', email:'Correo', phone:'Teléfono', birth:'Nacimiento', state:'Estado', municipality:'Municipio', address:'Dirección', degree:'Último grado', institution:'Institución', average:'Promedio', languages:'Idiomas', publications:'Publicaciones', experience:'Experiencia', department:'Departamento', section:'Sección', program:'Programa', mode:'Modalidad', advisor:'Tutor', examsTitle:'Exámenes de admisión y selección', minutes:'minutos'},
    profile:{photo:'Foto de perfil', update:'Actualiza tus datos de contacto y tu foto.', selectImage:'Selecciona una imagen válida.', maxPhoto:'La foto no debe superar 5 MB.', saved:'Perfil actualizado correctamente.', unexpected:'El servidor devolvió una respuesta inesperada al actualizar el perfil.', saveError:'No se pudo actualizar el perfil.', name:'Nombre completo', email:'Correo electrónico', phone:'Teléfono', save:'Guardar cambios', saving:'Guardando...', fileHelp:'JPG, PNG o WebP · máximo 5 MB'},
    documents:{title:'Documentos requeridos', intro:'Carga archivos PDF de hasta 10 MB. Cada carga queda registrada y se notifica al flujo LIDA.', requirements:[['Currículum vitae','PDF con formación, experiencia y publicaciones.'],['Título o comprobante de estudios','Título, cédula o constancia académica.'],['Carta de motivos','Explica tu interés por el programa.'],['Carta de recomendación','Carta firmada por una referencia académica o profesional.']], unexpected:'El servidor devolvió una respuesta inesperada.', loadError:'No se pudieron cargar tus documentos.', invalidResponse:'La respuesta del servidor no fue válida.', pdfOnly:'Solo puedes cargar archivos PDF.', maxFile:'Cada archivo debe pesar como máximo 10 MB.', saveError:'No se pudo guardar el documento.', tryAgain:'Intenta nuevamente.', deleteConfirm:'¿Eliminar', deleteError:'No se pudo eliminar el documento.', downloadError:'No se pudo descargar el documento.', loaded:'Cargado', notified:'Notificado a LIDA', pendingNotice:'Pendiente de notificación LIDA', replace:'Reemplazar', delete:'Eliminar', uploading:'Cargando...', choosePdf:'Seleccionar PDF', saveUnexpected:'El servidor devolvió una respuesta inesperada. Intenta nuevamente.'},
    support:{title:'Solicitud de apoyo', locked:'Este formulario se habilitará cuando Coordinación Académica registre que aprobaste el curso propedéutico con una calificación mínima de 8.', registered:'Tu solicitud de apoyo está registrada. Ya puedes imprimir la hoja formal.', print:'Imprimir solicitud de apoyo', intro:'Captura los datos bancarios para registrar tu solicitud de apoyo académico.', bank:'Nombre del banco', clabe:'CLABE interbancaria', exampleBank:'Ej. BBVA México', digits:'18 dígitos', validation:'Captura el banco y una CLABE interbancaria de 18 dígitos.', saveError:'No se pudo guardar la solicitud.', save:'Guardar datos y solicitar apoyo', saving:'Guardando...', requestDate:'Fecha de solicitud', folio:'Folio', applicant:'Nombre del aspirante', declaration:'Por medio de la presente, solicito el apoyo académico correspondiente y proporciono los datos bancarios para los fines administrativos aplicables.', accuracy:'Declaro que los datos proporcionados son correctos y autorizo su uso exclusivamente para la gestión administrativa del apoyo solicitado.', signature:'Firma del aspirante', approval:'Vo. Bo. Coordinación Académica', generated:'Documento generado por SINAC NEXT · Cinvestav', institution:'CENTRO DE INVESTIGACIÓN Y DE ESTUDIOS AVANZADOS', institute:'DEL INSTITUTO POLITÉCNICO NACIONAL', printTitle:'Solicitud de apoyo académico'},
    followup:{title:'Seguimiento de tu solicitud', intro:'Consulta los cambios registrados en tu proceso de admisión.', update:'Actualizar', loading:'Cargando seguimiento...', empty:'Aún no hay movimientos registrados.', lida:'Enlace LIDA', currentState:'Estado actual', businessKey:'Clave de negocio', instance:'Instancia Camunda', pendingAssignment:'Pendiente de asignación'},
  },
  en: {
    locale:'en-US', panelTitle:'Applicant Panel', loading:'Loading...', requestFallback:'Your application', loadingRequest:'Loading your application information...', retry:'Retry', sidebarTitle:'Sections', sidebarHint:'Open a section to view its contents.', logout:'Log out', notifications:'Notifications',
    menu:{perfil:'My profile', inicio:'Home', expediente:'Academic record', proceso:'LIDA tracking', documentos:'Documents', examenes:'Online exams'},
    stages:{pendiente:'Pre-registration received', iniciado:'Process started', revision:'Under review', aceptado:'Accepted', rechazado:'Not accepted', baja:'Withdrawn'},
    stageMessages:{pendiente:'Your pre-registration was received. Academic Coordination will review it soon.', iniciado:'The LIDA workflow has started and will soon be reviewed.', revision:'Academic Coordination is reviewing your record.', aceptado:'Congratulations! Your application was accepted.', rechazado:'Your application was not accepted. Review the notes or contact Academic Coordination.', baja:'Your registration was withdrawn. Contact Academic Coordination for more information.'},
    messages:{sessionExpired:'Your session has expired. Sign in again to continue.', profileLoadError:'Your profile could not be loaded. Check your connection and try again.', trackingError:'Your application tracking could not be loaded.', conversionDeclined:'You can request support once more later if you need it.', conversionSuccess:'Your account is now active as a student. Sign in again with the same credentials to open the student panel.', conversionLogout:'Your account was converted to a student account. Sign in again to continue.', conversionError:'The transition could not be completed.', noNotifications:'There are no recent notifications.', loadingNotifications:'Loading notifications...', noExams:'No exams have been assigned yet.', noRecord:'No digital record is available.', integratingRecord:'Loading your digital record...', noEvents:'No activity has been recorded yet.'},
    conversion:{aria:'Transition confirmation', title:'Continue as a student', question:'Would you like to convert your account to a student account and open the corresponding panel with the same credentials?', cancel:'No, remind me later', confirm:'Yes, continue', processing:'Processing...'},
    overview:{summary:'Application summary', currentStage:'Current stage', currentModality:'Study mode', currentUnit:'Unit', low:'Registration withdrawn', rejected:'Application not accepted', quick:'Quick access', fullRecord:'View full record', track:'View LIDA process', continueStudent:'Continue as a student', next:'Next step', stage:'Current stage', recentNotifications:'Recent notifications', update:'Refresh', centralRecord:'CENTRALIZED STUDENT RECORD', thesis:'Thesis progress', defense:'Defense', signatures:'Electronic signatures', personal:'Personal information', addresses:'Addresses', current:'Current', permanent:'Permanent', education:'Education', affiliation:'Academic affiliation', documents:'Documents', enrollments:'Enrollments', requests:'Requests', signaturesCount:'Signatures', thesisProjects:'Thesis projects', movements:'Activity', name:'Name', curp:'CURP', email:'Email', phone:'Phone', birth:'Date of birth', state:'State', municipality:'City / municipality', address:'Address', degree:'Highest degree', institution:'Institution', average:'Grade average', languages:'Languages', publications:'Publications', experience:'Experience', department:'Department', section:'Section', program:'Program', mode:'Study mode', advisor:'Advisor', examsTitle:'Admission and selection exams', minutes:'minutes'},
    profile:{photo:'Profile photo', update:'Update your contact details and photo.', selectImage:'Select a valid image.', maxPhoto:'The photo must not exceed 5 MB.', saved:'Profile updated successfully.', unexpected:'The server returned an unexpected response while updating your profile.', saveError:'The profile could not be updated.', name:'Full name', email:'Email address', phone:'Phone', save:'Save changes', saving:'Saving...', fileHelp:'JPG, PNG or WebP · up to 5 MB'},
    documents:{title:'Required documents', intro:'Upload PDF files up to 10 MB. Each upload is recorded and reported to the LIDA workflow.', requirements:[['Resume','PDF with education, experience, and publications.'],['Degree or proof of studies','Degree, license, or academic certificate.'],['Statement of purpose','Explain your interest in the program.'],['Letter of recommendation','Letter signed by an academic or professional reference.']], unexpected:'The server returned an unexpected response.', loadError:'Your documents could not be loaded.', invalidResponse:'The server response was invalid.', pdfOnly:'Only PDF files can be uploaded.', maxFile:'Each file must be no larger than 10 MB.', saveError:'The document could not be saved.', tryAgain:'Please try again.', deleteConfirm:'Delete', deleteError:'The document could not be deleted.', downloadError:'The document could not be downloaded.', loaded:'Uploaded', notified:'Reported to LIDA', pendingNotice:'Pending LIDA notification', replace:'Replace', delete:'Delete', uploading:'Uploading...', choosePdf:'Choose PDF', saveUnexpected:'The server returned an unexpected response. Please try again.'},
    support:{title:'Financial support request', locked:'This form will be available after Academic Coordination records that you passed the preparatory course with a grade of at least 8.', registered:'Your support request is registered. You can now print the formal document.', print:'Print support request', intro:'Enter your bank details to register your academic support request.', bank:'Bank name', clabe:'Interbank CLABE', exampleBank:'e.g. BBVA México', digits:'18 digits', validation:'Enter a bank name and an 18-digit interbank CLABE.', saveError:'The request could not be saved.', save:'Save details and request support', saving:'Saving...', requestDate:'Request date', folio:'Reference', applicant:'Applicant name', declaration:'I request the corresponding academic support and provide my bank details for applicable administrative purposes.', accuracy:'I declare that the information provided is correct and authorize its use solely to administer the requested support.', signature:'Applicant signature', approval:'Academic Coordination approval', generated:'Document generated by SINAC NEXT · Cinvestav', institution:'CENTER FOR RESEARCH AND ADVANCED STUDIES', institute:'OF THE NATIONAL POLYTECHNIC INSTITUTE', printTitle:'Academic support request'},
    followup:{title:'Application tracking', intro:'Review updates recorded during your admission process.', update:'Refresh', loading:'Loading tracking...', empty:'No activity has been recorded yet.', lida:'LIDA link', currentState:'Current status', businessKey:'Business key', instance:'Camunda instance', pendingAssignment:'Pending assignment'},
  },
  de: {
    locale:'de-DE', panelTitle:'Bewerberbereich', loading:'Wird geladen...', requestFallback:'Ihr Antrag', loadingRequest:'Antragsdaten werden geladen...', retry:'Erneut versuchen', sidebarTitle:'Abschnitte', sidebarHint:'Öffnen Sie einen Abschnitt, um dessen Inhalt anzuzeigen.', logout:'Abmelden', notifications:'Benachrichtigungen',
    menu:{perfil:'Mein Profil', inicio:'Startseite', expediente:'Akte', proceso:'LIDA-Verlauf', documentos:'Dokumente', examenes:'Online-Prüfungen'},
    stages:{pendiente:'Vorregistrierung eingegangen', iniciado:'Verfahren gestartet', revision:'In Prüfung', aceptado:'Angenommen', rechazado:'Nicht angenommen', baja:'Abgemeldet'},
    stageMessages:{pendiente:'Ihre Vorregistrierung ist eingegangen. Die akademische Koordination wird sie bald prüfen.', iniciado:'Der LIDA-Ablauf wurde gestartet und wird bald geprüft.', revision:'Die akademische Koordination prüft Ihre Akte.', aceptado:'Herzlichen Glückwunsch! Ihr Antrag wurde angenommen.', rechazado:'Ihr Antrag wurde nicht angenommen. Prüfen Sie die Hinweise oder wenden Sie sich an die akademische Koordination.', baja:'Ihre Registrierung wurde beendet. Wenden Sie sich für weitere Informationen an die akademische Koordination.'},
    messages:{sessionExpired:'Ihre Sitzung ist abgelaufen. Melden Sie sich erneut an.', profileLoadError:'Ihr Profil konnte nicht geladen werden. Prüfen Sie Ihre Verbindung und versuchen Sie es erneut.', trackingError:'Der Verfahrensverlauf konnte nicht geladen werden.', conversionDeclined:'Bei Bedarf können Sie später erneut Unterstützung anfordern.', conversionSuccess:'Ihr Konto ist jetzt als Studierendenkonto aktiv. Melden Sie sich mit denselben Zugangsdaten erneut an.', conversionLogout:'Ihr Konto wurde in ein Studierendenkonto umgewandelt. Melden Sie sich erneut an.', conversionError:'Der Wechsel konnte nicht abgeschlossen werden.', noNotifications:'Keine neuen Benachrichtigungen.', loadingNotifications:'Benachrichtigungen werden geladen...', noExams:'Ihnen wurden noch keine Prüfungen zugewiesen.', noRecord:'Keine digitale Akte verfügbar.', integratingRecord:'Digitale Akte wird geladen...', noEvents:'Es sind noch keine Aktivitäten erfasst.'},
    conversion:{aria:'Bestätigung des Kontowechsels', title:'Als Studierende fortfahren', question:'Möchten Sie Ihr Konto jetzt in ein Studierendenkonto umwandeln und sich mit denselben Zugangsdaten anmelden?', cancel:'Nein, später erinnern', confirm:'Ja, fortfahren', processing:'Wird verarbeitet...'},
    overview:{summary:'Zusammenfassung Ihres Antrags', currentStage:'Aktuelle Phase', currentModality:'Studienform', currentUnit:'Einheit', low:'Registrierung beendet', rejected:'Antrag nicht angenommen', quick:'Schnellzugriff', fullRecord:'Vollständige Akte anzeigen', track:'LIDA-Verfahren anzeigen', continueStudent:'Als Studierende fortfahren', next:'Nächster Schritt', stage:'Aktuelle Phase', recentNotifications:'Letzte Benachrichtigungen', update:'Aktualisieren', centralRecord:'ZENTRALE STUDIERENDENAKTE', thesis:'Dissertationsverlauf', defense:'Verteidigung', signatures:'Elektronische Signaturen', personal:'Persönliche Angaben', addresses:'Anschriften', current:'Aktuell', permanent:'Dauerhaft', education:'Ausbildung', affiliation:'Akademische Zuordnung', documents:'Dokumente', enrollments:'Einschreibungen', requests:'Anträge', signaturesCount:'Signaturen', thesisProjects:'Dissertationsprojekte', movements:'Aktivitäten', name:'Name', curp:'CURP', email:'E-Mail', phone:'Telefon', birth:'Geburtsdatum', state:'Bundesstaat', municipality:'Ort / Gemeinde', address:'Anschrift', degree:'Höchster Abschluss', institution:'Einrichtung', average:'Notendurchschnitt', languages:'Sprachen', publications:'Veröffentlichungen', experience:'Erfahrung', department:'Abteilung', section:'Bereich', program:'Studiengang', mode:'Studienform', advisor:'Betreuung', examsTitle:'Aufnahme- und Auswahlprüfungen', minutes:'Minuten'},
    profile:{photo:'Profilfoto', update:'Kontaktdaten und Foto aktualisieren.', selectImage:'Bitte wählen Sie ein gültiges Bild aus.', maxPhoto:'Das Foto darf höchstens 5 MB groß sein.', saved:'Profil erfolgreich aktualisiert.', unexpected:'Unerwartete Serverantwort beim Aktualisieren des Profils.', saveError:'Das Profil konnte nicht aktualisiert werden.', name:'Vollständiger Name', email:'E-Mail-Adresse', phone:'Telefon', save:'Änderungen speichern', saving:'Wird gespeichert...', fileHelp:'JPG, PNG oder WebP · maximal 5 MB'},
    documents:{title:'Erforderliche Dokumente', intro:'Laden Sie PDF-Dateien bis 10 MB hoch. Jeder Upload wird erfasst und an den LIDA-Ablauf gemeldet.', requirements:[['Lebenslauf','PDF mit Ausbildung, Erfahrung und Veröffentlichungen.'],['Abschluss oder Studiennachweis','Abschluss, Berufszulassung oder Studienbescheinigung.'],['Motivationsschreiben','Erläutern Sie Ihr Interesse am Studiengang.'],['Empfehlungsschreiben','Von einer akademischen oder beruflichen Referenz unterschrieben.']], unexpected:'Unerwartete Serverantwort.', loadError:'Dokumente konnten nicht geladen werden.', invalidResponse:'Ungültige Serverantwort.', pdfOnly:'Es können nur PDF-Dateien hochgeladen werden.', maxFile:'Jede Datei darf höchstens 10 MB groß sein.', saveError:'Dokument konnte nicht gespeichert werden.', tryAgain:'Bitte versuchen Sie es erneut.', deleteConfirm:'Löschen', deleteError:'Dokument konnte nicht gelöscht werden.', downloadError:'Dokument konnte nicht heruntergeladen werden.', loaded:'Hochgeladen', notified:'An LIDA gemeldet', pendingNotice:'LIDA-Benachrichtigung ausstehend', replace:'Ersetzen', delete:'Löschen', uploading:'Wird hochgeladen...', choosePdf:'PDF auswählen', saveUnexpected:'Unerwartete Serverantwort. Bitte versuchen Sie es erneut.'},
    support:{title:'Förderantrag', locked:'Dieses Formular wird freigeschaltet, sobald die akademische Koordination das Bestehen des Vorbereitungskurses mit mindestens 8 bestätigt.', registered:'Ihr Förderantrag ist registriert. Sie können das offizielle Formular drucken.', print:'Förderantrag drucken', intro:'Geben Sie Ihre Bankdaten für den akademischen Förderantrag ein.', bank:'Bankname', clabe:'Interbank-CLABE', exampleBank:'z. B. BBVA México', digits:'18 Ziffern', validation:'Geben Sie eine Bank und eine 18-stellige Interbank-CLABE ein.', saveError:'Der Antrag konnte nicht gespeichert werden.', save:'Daten speichern und Förderung beantragen', saving:'Wird gespeichert...', requestDate:'Antragsdatum', folio:'Referenz', applicant:'Name des Bewerbers', declaration:'Hiermit beantrage ich die entsprechende akademische Förderung und gebe meine Bankdaten für die Verwaltung an.', accuracy:'Ich bestätige die Richtigkeit der Angaben und genehmige ihre ausschließliche Verwendung für die Verwaltung der beantragten Förderung.', signature:'Unterschrift des Bewerbers', approval:'Freigabe durch die akademische Koordination', generated:'Dokument erstellt von SINAC NEXT · Cinvestav', institution:'ZENTRUM FÜR FORSCHUNG UND FORTGESCHRITTENE STUDIEN', institute:'DES NATIONALEN POLYTECHNISCHEN INSTITUTS', printTitle:'Antrag auf akademische Förderung'},
    followup:{title:'Verfahrensverlauf', intro:'Sehen Sie sich die Änderungen Ihres Zulassungsverfahrens an.', update:'Aktualisieren', loading:'Verlauf wird geladen...', empty:'Es sind noch keine Aktivitäten erfasst.', lida:'LIDA-Verknüpfung', currentState:'Aktueller Status', businessKey:'Geschäftsschlüssel', instance:'Camunda-Instanz', pendingAssignment:'Zuweisung ausstehend'},
  },
  zh: {
    locale:'zh-CN', panelTitle:'申请人面板', loading:'正在加载...', requestFallback:'您的申请', loadingRequest:'正在加载申请信息...', retry:'重试', sidebarTitle:'栏目', sidebarHint:'打开栏目查看内容。', logout:'退出登录', notifications:'通知',
    menu:{perfil:'我的资料', inicio:'首页', expediente:'个人档案', proceso:'LIDA 进度', documentos:'文件', examenes:'在线考试'},
    stages:{pendiente:'已收到预注册', iniciado:'流程已启动', revision:'审核中', aceptado:'已录取', rechazado:'未录取', baja:'已注销'},
    stageMessages:{pendiente:'已收到您的预注册，学术协调部门将尽快审核。', iniciado:'LIDA 流程已启动，即将进入审核。', revision:'学术协调部门正在审核您的档案。', aceptado:'恭喜！您的申请已获录取。', rechazado:'您的申请未获录取。请查看备注或联系学术协调部门。', baja:'您的注册已注销。如需了解详情，请联系学术协调部门。'},
    messages:{sessionExpired:'登录已过期，请重新登录。', profileLoadError:'无法加载个人资料，请检查网络后重试。', trackingError:'无法加载申请进度。', conversionDeclined:'如之后需要，您还可以再次申请资助。', conversionSuccess:'您的账户已启用为学生账户。请使用相同凭据重新登录。', conversionLogout:'账户已转换为学生账户，请重新登录继续。', conversionError:'无法完成账户转换。', noNotifications:'暂无近期通知。', loadingNotifications:'正在加载通知...', noExams:'目前没有分配考试。', noRecord:'暂无电子档案。', integratingRecord:'正在加载电子档案...', noEvents:'暂无流程记录。'},
    conversion:{aria:'账户转换确认', title:'以学生身份继续', question:'现在要将账户转换为学生账户，并使用相同凭据进入相应面板吗？', cancel:'暂不，稍后提醒', confirm:'是，继续', processing:'正在处理...'},
    overview:{summary:'申请摘要', currentStage:'当前阶段', currentModality:'学习方式', currentUnit:'单位', low:'注册已注销', rejected:'申请未获录取', quick:'快捷入口', fullRecord:'查看完整档案', track:'查看 LIDA 流程', continueStudent:'以学生身份继续', next:'下一步', stage:'当前阶段', recentNotifications:'近期通知', update:'刷新', centralRecord:'集中式学生档案', thesis:'论文进度', defense:'答辩', signatures:'电子签名', personal:'个人信息', addresses:'地址', current:'当前', permanent:'常住', education:'教育背景', affiliation:'学术归属', documents:'文件', enrollments:'选课', requests:'申请', signaturesCount:'签名', thesisProjects:'论文项目', movements:'动态', name:'姓名', curp:'CURP', email:'电子邮件', phone:'电话', birth:'出生日期', state:'州', municipality:'市 / 县', address:'地址', degree:'最高学历', institution:'院校', average:'平均成绩', languages:'语言', publications:'出版物', experience:'经历', department:'部门', section:'组别', program:'项目', mode:'学习方式', advisor:'导师', examsTitle:'入学与选拔考试', minutes:'分钟'},
    profile:{photo:'头像', update:'更新联系方式和头像。', selectImage:'请选择有效图片。', maxPhoto:'图片不得超过 5 MB。', saved:'资料更新成功。', unexpected:'更新资料时服务器返回了意外响应。', saveError:'无法更新资料。', name:'姓名', email:'电子邮件', phone:'电话', save:'保存更改', saving:'正在保存...', fileHelp:'JPG、PNG 或 WebP · 最大 5 MB'},
    documents:{title:'所需文件', intro:'上传不超过 10 MB 的 PDF 文件。每次上传都会记录并通知 LIDA 流程。', requirements:[['个人简历','包含教育、经历和出版物的 PDF。'],['学位或学习证明','学位证、执业证或在读证明。'],['动机信','说明您对该项目的兴趣。'],['推荐信','由学术或职业推荐人签署。']], unexpected:'服务器返回了意外响应。', loadError:'无法加载文件。', invalidResponse:'服务器响应无效。', pdfOnly:'只能上传 PDF 文件。', maxFile:'每个文件最大为 10 MB。', saveError:'无法保存文件。', tryAgain:'请重试。', deleteConfirm:'删除', deleteError:'无法删除文件。', downloadError:'无法下载文件。', loaded:'已上传', notified:'已通知 LIDA', pendingNotice:'等待通知 LIDA', replace:'替换', delete:'删除', uploading:'正在上传...', choosePdf:'选择 PDF', saveUnexpected:'服务器返回了意外响应，请重试。'},
    support:{title:'资助申请', locked:'学术协调部门确认预科课程成绩至少为 8 后，此表单将开放。', registered:'资助申请已登记，可以打印正式表单。', print:'打印资助申请', intro:'填写银行信息以登记学术资助申请。', bank:'银行名称', clabe:'银行间 CLABE', exampleBank:'例如 BBVA México', digits:'18 位数字', validation:'请输入银行名称和 18 位银行间 CLABE。', saveError:'无法保存申请。', save:'保存信息并申请资助', saving:'正在保存...', requestDate:'申请日期', folio:'编号', applicant:'申请人姓名', declaration:'本人申请相应学术资助，并提供银行信息以用于相关行政管理。', accuracy:'本人声明所提供信息真实准确，并授权仅将其用于所申请资助的行政管理。', signature:'申请人签名', approval:'学术协调部门批准', generated:'由 SINAC NEXT · Cinvestav 生成', institution:'研究与高级研究中心', institute:'墨西哥国家理工学院', printTitle:'学术资助申请'},
    followup:{title:'申请进度', intro:'查看录取流程中的记录更新。', update:'刷新', loading:'正在加载进度...', empty:'暂无流程记录。', lida:'LIDA 链接', currentState:'当前状态', businessKey:'业务密钥', instance:'Camunda 实例', pendingAssignment:'等待分配'},
  },
  pt: {
    locale:'pt-BR', panelTitle:'Painel do Candidato', loading:'Carregando...', requestFallback:'Sua solicitação', loadingRequest:'Carregando os dados da sua solicitação...', retry:'Tentar novamente', sidebarTitle:'Seções', sidebarHint:'Abra uma seção para ver o conteúdo.', logout:'Sair', notifications:'Notificações',
    menu:{perfil:'Meu perfil', inicio:'Início', expediente:'Documentação', proceso:'Acompanhamento LIDA', documentos:'Documentos', examenes:'Provas on-line'},
    stages:{pendiente:'Pré-cadastro recebido', iniciado:'Processo iniciado', revision:'Em análise', aceptado:'Aceito', rechazado:'Não aceito', baja:'Cancelado'},
    stageMessages:{pendiente:'Seu pré-cadastro foi recebido. A Coordenação Acadêmica irá analisá-lo em breve.', iniciado:'O fluxo LIDA foi iniciado e será analisado em breve.', revision:'A Coordenação Acadêmica está analisando sua documentação.', aceptado:'Parabéns! Sua solicitação foi aceita.', rechazado:'Sua solicitação não foi aceita. Consulte as observações ou fale com a Coordenação Acadêmica.', baja:'Seu cadastro foi cancelado. Entre em contato com a Coordenação Acadêmica para obter informações.'},
    messages:{sessionExpired:'Sua sessão expirou. Entre novamente para continuar.', profileLoadError:'Não foi possível carregar seu perfil. Verifique a conexão e tente novamente.', trackingError:'Não foi possível carregar o acompanhamento.', conversionDeclined:'Se precisar, você poderá solicitar apoio novamente mais tarde.', conversionSuccess:'Sua conta agora está ativa como aluno. Entre novamente com as mesmas credenciais para acessar o painel do aluno.', conversionLogout:'Sua conta foi convertida em conta de aluno. Entre novamente para continuar.', conversionError:'Não foi possível concluir a transição.', noNotifications:'Não há notificações recentes.', loadingNotifications:'Carregando notificações...', noExams:'Ainda não há provas atribuídas.', noRecord:'Não há documentação digital disponível.', integratingRecord:'Integrando documentação digital...', noEvents:'Ainda não há movimentações registradas.'},
    conversion:{aria:'Confirmação de transição', title:'Continuar como aluno', question:'Deseja converter sua conta em conta de aluno e acessar o painel correspondente com as mesmas credenciais?', cancel:'Não, lembrar depois', confirm:'Sim, continuar', processing:'Processando...'},
    overview:{summary:'Resumo da solicitação', currentStage:'Etapa atual', currentModality:'Modalidade', currentUnit:'Unidade', low:'Cadastro cancelado', rejected:'Solicitação não aceita', quick:'Acesso rápido', fullRecord:'Ver documentação completa', track:'Ver processo LIDA', continueStudent:'Continuar como aluno', next:'Próxima etapa', stage:'Etapa atual', recentNotifications:'Notificações recentes', update:'Atualizar', centralRecord:'DOCUMENTAÇÃO CENTRALIZADA DO ALUNO', thesis:'Andamento da tese', defense:'Defesa', signatures:'Assinaturas eletrônicas', personal:'Dados pessoais', addresses:'Endereços', current:'Atual', permanent:'Permanente', education:'Escolaridade', affiliation:'Vínculo acadêmico', documents:'Documentos', enrollments:'Inscrições', requests:'Solicitações', signaturesCount:'Assinaturas', thesisProjects:'Projetos de tese', movements:'Movimentações', name:'Nome', curp:'CURP', email:'E-mail', phone:'Telefone', birth:'Nascimento', state:'Estado', municipality:'Município', address:'Endereço', degree:'Último grau', institution:'Instituição', average:'Média', languages:'Idiomas', publications:'Publicações', experience:'Experiência', department:'Departamento', section:'Seção', program:'Programa', mode:'Modalidade', advisor:'Orientador', examsTitle:'Provas de admissão e seleção', minutes:'minutos'},
    profile:{photo:'Foto do perfil', update:'Atualize seus dados de contato e sua foto.', selectImage:'Selecione uma imagem válida.', maxPhoto:'A foto não pode ultrapassar 5 MB.', saved:'Perfil atualizado com sucesso.', unexpected:'O servidor retornou uma resposta inesperada ao atualizar o perfil.', saveError:'Não foi possível atualizar o perfil.', name:'Nome completo', email:'E-mail', phone:'Telefone', save:'Salvar alterações', saving:'Salvando...', fileHelp:'JPG, PNG ou WebP · máximo 5 MB'},
    documents:{title:'Documentos necessários', intro:'Envie arquivos PDF de até 10 MB. Cada envio é registrado e notificado no fluxo LIDA.', requirements:[['Currículo','PDF com formação, experiência e publicações.'],['Diploma ou comprovante de estudos','Diploma, registro ou declaração acadêmica.'],['Carta de motivação','Explique seu interesse pelo programa.'],['Carta de recomendação','Assinada por uma referência acadêmica ou profissional.']], unexpected:'O servidor retornou uma resposta inesperada.', loadError:'Não foi possível carregar seus documentos.', invalidResponse:'A resposta do servidor é inválida.', pdfOnly:'Só é possível enviar arquivos PDF.', maxFile:'Cada arquivo pode ter no máximo 10 MB.', saveError:'Não foi possível salvar o documento.', tryAgain:'Tente novamente.', deleteConfirm:'Excluir', deleteError:'Não foi possível excluir o documento.', downloadError:'Não foi possível baixar o documento.', loaded:'Enviado', notified:'Notificado ao LIDA', pendingNotice:'Notificação ao LIDA pendente', replace:'Substituir', delete:'Excluir', uploading:'Enviando...', choosePdf:'Selecionar PDF', saveUnexpected:'O servidor retornou uma resposta inesperada. Tente novamente.'},
    support:{title:'Solicitação de apoio', locked:'Este formulário será liberado quando a Coordenação Acadêmica registrar sua aprovação no curso propedêutico com nota mínima 8.', registered:'Sua solicitação de apoio está registrada. Você já pode imprimir o documento formal.', print:'Imprimir solicitação de apoio', intro:'Informe os dados bancários para registrar sua solicitação de apoio acadêmico.', bank:'Nome do banco', clabe:'CLABE interbancária', exampleBank:'Ex.: BBVA México', digits:'18 dígitos', validation:'Informe o banco e uma CLABE interbancária de 18 dígitos.', saveError:'Não foi possível salvar a solicitação.', save:'Salvar dados e solicitar apoio', saving:'Salvando...', requestDate:'Data da solicitação', folio:'Protocolo', applicant:'Nome do candidato', declaration:'Solicito o apoio acadêmico correspondente e forneço meus dados bancários para os fins administrativos aplicáveis.', accuracy:'Declaro que os dados fornecidos são corretos e autorizo seu uso exclusivamente para a gestão administrativa do apoio solicitado.', signature:'Assinatura do candidato', approval:'Aprovação da Coordenação Acadêmica', generated:'Documento gerado por SINAC NEXT · Cinvestav', institution:'CENTRO DE PESQUISA E DE ESTUDOS AVANÇADOS', institute:'DO INSTITUTO POLITÉCNICO NACIONAL', printTitle:'Solicitação de apoio acadêmico'},
    followup:{title:'Acompanhamento da solicitação', intro:'Consulte as atualizações registradas no seu processo de admissão.', update:'Atualizar', loading:'Carregando acompanhamento...', empty:'Ainda não há movimentações registradas.', lida:'Vínculo LIDA', currentState:'Status atual', businessKey:'Chave de negócio', instance:'Instância Camunda', pendingAssignment:'Aguardando atribuição'},
  },
};

export function useApplicantCopy() {
  const {language} = useLanguage();
  return copy[language] || copy.es;
}