import {useLanguage} from '../translations';

const catalog = {
  es:{
    locale:'es-MX',panel:'Panel de docente',kicker:'Docencia',operations:'OPERACIÓN ACADÉMICA',brand:'Docente',brandSubtitle:'Evaluación y seguimiento',logout:'Cerrar sesión',refresh:'Actualizar',loading:'Cargando panel del docente...',loadingData:'Cargando datos...',
    groups:{overview:'Panorama',teaching:'Docencia',evaluation:'Evaluación',followup:'Seguimiento'},menu:{overview:'Resumen',cursos:'Mis cursos',carga:'Mi carga académica',catalogo:'Elegir materia',estudiantes:'Estudiantes',calificaciones:'Calificaciones',examenes:'Exámenes',entrevistas:'Entrevistas',solicitudes:'Solicitudes',reportes:'Reportes',perfil:'Mi perfil'},
    status:{cursando:'Cursando',aprobada:'Aprobada',reprobada:'Reprobada',pendiente:'Pendiente',aceptado:'Aceptado',rechazado:'Rechazado',programado:'Programado',iniciado:'Iniciado',completado:'Completado',aprobado:'Aprobado',cancelado:'Cancelado',programada:'Programada',iniciada:'Iniciada',completada:'Completada',cancelada:'Cancelada'},
    common:{student:'Estudiante',students:'Estudiantes',user:'Usuario',program:'Programa',status:'Estado',academicStatus:'Estado académico',grade:'Calificación',final:'Final',partials:'Parciales',course:'Curso',credits:'Créditos',teacher:'Docente',schedule:'Horario',date:'Fecha',duration:'Duración',minutes:'minutos',pending:'Pendiente',notAssigned:'Profesor no asignado',periodMissing:'Sin periodo asignado',update:'Actualizar',export:'Exportar',registerGrade:'Registrar calificación',newGrade:'Nueva calificación',noStudents:'No hay alumnos inscritos en esta materia.',noSubjects:'No hay materias asignadas actualmente.',noRequests:'Sin solicitudes',allResolved:'Todas resueltas',view:'Ver',noComment:'Sin comentario.',actions:'Acciones',selectStudent:'Selecciona un estudiante'},
    overview:{courses:'Mis cursos',assigned:'Materias asignadas',students:'Estudiantes',enrolled:'Total inscrito',passed:'Aprobados',recent:'Últimas sesiones',exams:'Exámenes',online:'Total en línea',interviews:'Entrevistas',scheduled:'Total programadas',requests:'Solicitudes',toReview:'Pendientes de revisar',courseKicker:'Cursos',mySubjects:'Mis materias este semestre',activity:'Actividad',noSubjects:'No hay materias asignadas actualmente.',schedule:'Horario',activityRequest:'Solicitud'},
    load:{kicker:'Flujo de aprobación',title:'Mi carga académica',intro:'Envía tu propuesta de carga a Coordinación Académica para revisión.',period:'Periodo',periodPlaceholder:'Periodo escolar (ej. 2026-1)',send:'Enviar a revisión',refresh:'Actualizar',noLoads:'Aún no has enviado cargas académicas.',noPeriod:'Sin periodo',open:'Inscripciones abiertas',closed:'Inscripciones cerradas',approve:'Aprobar',reject:'Rechazar',publish:'Publicar',sendError:'No se pudo enviar la carga.',loadError:'No se pudieron cargar las cargas académicas.',updateError:'No se pudo actualizar la carga.'},
    courses:{kicker:'Cursos',mySubjects:'Mis materias',key:'Clave',schedule:'Horario',back:'Volver',enrolled:'Estudiantes inscritos',name:'Nombre',user:'Usuario',program:'Programa',selectTitle:'Oferta académica',choose:'Elige la materia que impartirás',intro:'Coordinación Académica carga el catálogo. Selecciona una materia disponible y registra el horario y salón.',professor:'Profesor',available:'Disponible',of:'de',students:'alumnos',schedulePlaceholder:'Ej. lunes y miércoles 08:00-10:00',room:'Salón',selectRoom:'Selecciona salón',roomOne:'Salón 1 - máximo 42',roomLab:'Laboratorio Harold V. McIntosh',meetingRoom:'Sala de Juntas',assignedElsewhere:'Asignada a otro docente',updateSchedule:'Actualizar horario',selectSubject:'Seleccionar materia',catalogEmpty:'Coordinación aún no ha cargado materias.',scheduleMissing:'Escribe el horario antes de seleccionar la materia.',roomMissing:'Selecciona el salón antes de asignar la materia.',assignError:'No se pudo asignar la materia.',connectionError:'No se pudo conectar con el servidor.',assignSuccess:'Materia asignada correctamente.'},
    grading:{title:'Registro de calificaciones',kicker:'ACTAS POR MATERIA',intro:'Captura y consulta las calificaciones dentro del grupo correspondiente.',partial:'Parcial',number:'Número de parcial',final:'Final',save:'Guardar calificación',cancel:'Cancelar',studentRequired:'Selecciona un estudiante y captura la calificación.',saveError:'No se pudo registrar la calificación.',courseLoad:'No hay estudiantes o calificaciones para exportar.',exportHeaders:['Estudiante','Usuario','Curso','Programa','Parcial 1','Parcial 2','Parcial 3','Final','Estado'],academicStatus:'Estado académico',lastUpdate:'Actualización',registration:'Registrar calificación',course:'Cursos',export:'Exportar calificaciones'},
    exams:{title:'Exámenes en línea',kicker:'Evaluación',student:'Estudiante',type:'Tipo de examen',scheduled:'Fecha programada',status:'Estado',grade:'Calificación',attempts:'Intentos',actions:'Acciones',start:'Iniciar',finish:'Finalizar',gradeAction:'Calificar',none:'No hay exámenes en línea',startError:'No se pudo iniciar el examen.',updateError:'No se pudo actualizar el examen.',gradePrompt:'Calificación del examen (0 a 10):',gradeRange:'La calificación debe ser un número entre 0 y 10.',finalGrade:'Calificación final'},
    interviews:{title:'Entrevistas virtuales',kicker:'Comunicación',closeForm:'Cerrar formulario',schedule:'Programar entrevista',student:'Estudiante',selectStudent:'Selecciona un estudiante',purpose:'Propósito',purposeOptions:{admision:'Entrevista de admisión',seguimiento:'Seguimiento de progreso',tutoria:'Tutoría académica',orientacion:'Orientación vocacional',otro:'Otro'},titleField:'Título',date:'Fecha y hora',duration:'Duración (minutos)',description:'Descripción / indicaciones',descriptionPlaceholder:'Comparte al alumno el objetivo o preparación requerida.',save:'Programar y generar sala',saving:'Guardando…',jitsi:'La sala segura de Jitsi se genera automáticamente.',scheduled:'Fecha programada',jitsiCol:'Jitsi',notes:'Notas',join:'Abrir sala',available:'Disponible al iniciar',start:'Iniciar',finish:'Finalizar',cancel:'Cancelar',noActions:'Sin acciones',none:'No hay entrevistas virtuales',studentDateRequired:'Selecciona un estudiante y una fecha para programar la entrevista.',scheduleError:'No se pudo programar la entrevista.',updateError:'No se pudo actualizar la entrevista.',notesPrompt:'Notas de la entrevista (opcional):'},
    requests:{title:'Solicitudes académicas',kicker:'Gestión',student:'Estudiante',type:'Tipo de solicitud',comment:'Comentario',status:'Estado',date:'Fecha'},
    reports:{title:'Estadísticas generales',kicker:'Desempeño',analytics:'Desempeño académico',description:'Indicadores de grupos, evaluaciones y entrevistas a cargo del docente.',courses:'Cursos',students:'Estudiantes',exams:'Exámenes',interviews:'Entrevistas',passed:'Aprobados',failed:'Reprobados',completedExams:'Exámenes completados',completedInterviews:'Entrevistas completadas',totalStudents:'Total de estudiantes',unit:'Unidad'},
    messages:{expired:'Tu sesión ha caducado. Vuelve a iniciar sesión.',permission:'No tienes permisos de docente para acceder a este panel.',loadError:'No se pudo cargar el panel del docente.',noCatalog:'No se pudo cargar el catálogo.',noInterviews:'No se pudo cargar la entrevista.',noExam:'No se pudo cargar el examen.',courseError:'No se pudo cargar el panel.'},
  },
  en:{
    locale:'en-US',panel:'Teacher Panel',kicker:'Teaching',operations:'ACADEMIC OPERATIONS',brand:'Teacher',brandSubtitle:'Assessment and follow-up',logout:'Log out',refresh:'Refresh',loading:'Loading teacher panel...',loadingData:'Loading data...',groups:{overview:'Overview',teaching:'Teaching',evaluation:'Assessment',followup:'Follow-up'},menu:{overview:'Overview',cursos:'My courses',carga:'My course load',catalogo:'Choose a course',estudiantes:'Students',calificaciones:'Grades',examenes:'Exams',entrevistas:'Interviews',solicitudes:'Requests',reportes:'Reports',perfil:'My profile'},
    status:{cursando:'In progress',aprobada:'Passed',reprobada:'Failed',pendiente:'Pending',aceptado:'Accepted',rechazado:'Rejected',programado:'Scheduled',iniciado:'Started',completado:'Completed',aprobado:'Passed',cancelado:'Cancelled',programada:'Scheduled',iniciada:'Started',completada:'Completed',cancelada:'Cancelled'},
    common:{student:'Student',students:'Students',user:'Username',program:'Program',status:'Status',academicStatus:'Academic status',grade:'Grade',final:'Final',partials:'Partials',course:'Course',credits:'Credits',teacher:'Instructor',schedule:'Schedule',date:'Date',duration:'Duration',minutes:'minutes',pending:'Pending',notAssigned:'Instructor not assigned',periodMissing:'No term assigned',update:'Refresh',export:'Export',registerGrade:'Register grade',newGrade:'New grade',noStudents:'No students enrolled in this course.',noSubjects:'No courses are currently assigned.',noRequests:'No requests',allResolved:'All resolved',view:'View',noComment:'No comment.',actions:'Actions',selectStudent:'Select a student'},
    overview:{courses:'My courses',assigned:'Assigned courses',students:'Students',enrolled:'Total enrolled',passed:'Passed',recent:'Recent sessions',exams:'Exams',online:'Total online',interviews:'Interviews',scheduled:'Total scheduled',requests:'Requests',toReview:'Awaiting review',courseKicker:'Courses',mySubjects:'My courses this term',activity:'Activity',noSubjects:'No courses are currently assigned.',schedule:'Schedule',activityRequest:'Request'},
    load:{kicker:'Approval workflow',title:'My course load',intro:'Send your proposed course load to Academic Coordination for review.',period:'Term',periodPlaceholder:'Academic term (e.g. 2026-1)',send:'Send for review',refresh:'Refresh',noLoads:'You have not submitted a course load yet.',noPeriod:'No term',open:'Registrations open',closed:'Registrations closed',approve:'Approve',reject:'Reject',publish:'Publish',sendError:'Could not submit the course load.',loadError:'Could not load course loads.',updateError:'Could not update the course load.'},
    courses:{kicker:'Courses',mySubjects:'My courses',key:'Code',schedule:'Schedule',back:'Back',enrolled:'Enrolled students',name:'Name',user:'Username',program:'Program',selectTitle:'Course offering',choose:'Choose a course to teach',intro:'Academic Coordination maintains the catalog. Select an available course and enter its schedule and room.',professor:'Instructor',available:'Available',of:'of',students:'students',schedulePlaceholder:'e.g. Monday and Wednesday 08:00-10:00',room:'Room',selectRoom:'Select a room',roomOne:'Room 1 - capacity 42',roomLab:'Harold V. McIntosh Laboratory',meetingRoom:'Conference room',assignedElsewhere:'Assigned to another instructor',updateSchedule:'Update schedule',selectSubject:'Select course',catalogEmpty:'Academic Coordination has not uploaded courses yet.',scheduleMissing:'Enter a schedule before selecting the course.',roomMissing:'Select a room before assigning the course.',assignError:'Could not assign the course.',connectionError:'Could not connect to the server.',assignSuccess:'Course assigned successfully.'},
    grading:{title:'Grade entry',kicker:'GRADES BY COURSE',intro:'Enter and review grades within the corresponding group.',partial:'Partial',number:'Partial number',final:'Final',save:'Save grade',cancel:'Cancel',studentRequired:'Select a student and enter a grade.',saveError:'Could not record the grade.',courseLoad:'There are no students or grades to export.',exportHeaders:['Student','Username','Course','Program','Partial 1','Partial 2','Partial 3','Final','Status'],academicStatus:'Academic status',lastUpdate:'Updated',registration:'Register grade',course:'Courses',export:'Export grades'},
    exams:{title:'Online exams',kicker:'Assessment',student:'Student',type:'Exam type',scheduled:'Scheduled date',status:'Status',grade:'Grade',attempts:'Attempts',actions:'Actions',start:'Start',finish:'Finish',gradeAction:'Grade',none:'There are no online exams.',startError:'Could not start the exam.',updateError:'Could not update the exam.',gradePrompt:'Exam grade (0 to 10):',gradeRange:'Grade must be a number from 0 to 10.',finalGrade:'Final grade'},
    interviews:{title:'Virtual interviews',kicker:'Communication',closeForm:'Close form',schedule:'Schedule interview',student:'Student',selectStudent:'Select a student',purpose:'Purpose',purposeOptions:{admision:'Admission interview',seguimiento:'Progress follow-up',tutoria:'Academic tutoring',orientacion:'Career guidance',otro:'Other'},titleField:'Title',date:'Date and time',duration:'Duration (minutes)',description:'Description / instructions',descriptionPlaceholder:'Share the objective or preparation with the student.',save:'Schedule and create room',saving:'Saving…',jitsi:'A secure Jitsi room is created automatically.',scheduled:'Scheduled date',jitsiCol:'Jitsi',notes:'Notes',join:'Open room',available:'Available when started',start:'Start',finish:'Finish',cancel:'Cancel',noActions:'No actions',none:'There are no virtual interviews.',studentDateRequired:'Select a student and date to schedule the interview.',scheduleError:'Could not schedule the interview.',updateError:'Could not update the interview.',notesPrompt:'Interview notes (optional):'},
    requests:{title:'Academic requests',kicker:'Management',student:'Student',type:'Request type',comment:'Comment',status:'Status',date:'Date'},
    reports:{title:'General statistics',kicker:'Performance',analytics:'Academic performance',description:'Indicators for groups, assessments, and interviews assigned to the teacher.',courses:'Courses',students:'Students',exams:'Exams',interviews:'Interviews',passed:'Passed',failed:'Failed',completedExams:'Completed exams',completedInterviews:'Completed interviews',totalStudents:'Total students',unit:'Unit'},messages:{expired:'Your session expired. Sign in again.',permission:'You do not have teacher permissions for this panel.',loadError:'Could not load the teacher panel.',noCatalog:'Could not load the course catalog.',noInterviews:'Could not load the interview.',noExam:'Could not load the exam.',courseError:'Could not load the panel.'},
  },
  de:{
    locale:'de-DE',panel:'Lehrendenbereich',kicker:'Lehre',operations:'AKADEMISCHER BETRIEB',brand:'Lehrkraft',brandSubtitle:'Bewertung und Nachverfolgung',logout:'Abmelden',refresh:'Aktualisieren',loading:'Lehrendenbereich wird geladen...',loadingData:'Daten werden geladen...',groups:{overview:'Überblick',teaching:'Lehre',evaluation:'Bewertung',followup:'Nachverfolgung'},menu:{overview:'Übersicht',cursos:'Meine Kurse',carga:'Mein Lehrangebot',catalogo:'Kurs auswählen',estudiantes:'Studierende',calificaciones:'Noten',examenes:'Prüfungen',entrevistas:'Gespräche',solicitudes:'Anträge',reportes:'Berichte',perfil:'Mein Profil'},
    status:{cursando:'Laufend',aprobada:'Bestanden',reprobada:'Nicht bestanden',pendiente:'Ausstehend',aceptado:'Angenommen',rechazado:'Abgelehnt',programado:'Geplant',iniciado:'Gestartet',completado:'Abgeschlossen',aprobado:'Bestanden',cancelado:'Abgesagt',programada:'Geplant',iniciada:'Gestartet',completada:'Abgeschlossen',cancelada:'Abgesagt'},
    common:{student:'Studierende',students:'Studierende',user:'Benutzername',program:'Studiengang',status:'Status',academicStatus:'Akademischer Status',grade:'Note',final:'Endnote',partials:'Teilnoten',course:'Kurs',credits:'Credits',teacher:'Lehrkraft',schedule:'Stundenplan',date:'Datum',duration:'Dauer',minutes:'Minuten',pending:'Ausstehend',notAssigned:'Lehrkraft nicht zugewiesen',periodMissing:'Kein Zeitraum zugewiesen',update:'Aktualisieren',export:'Exportieren',registerGrade:'Note eintragen',newGrade:'Neue Note',noStudents:'Keine Studierenden in diesem Kurs eingeschrieben.',noSubjects:'Derzeit keine Kurse zugewiesen.',noRequests:'Keine Anträge',allResolved:'Alle erledigt',view:'Anzeigen',noComment:'Kein Kommentar.',actions:'Aktionen',selectStudent:'Studierende auswählen'},
    overview:{courses:'Meine Kurse',assigned:'Zugewiesene Kurse',students:'Studierende',enrolled:'Eingeschrieben insgesamt',passed:'Bestanden',recent:'Letzte Sitzungen',exams:'Prüfungen',online:'Online insgesamt',interviews:'Gespräche',scheduled:'Geplant insgesamt',requests:'Anträge',toReview:'Prüfung ausstehend',courseKicker:'Kurse',mySubjects:'Meine Kurse dieses Semester',activity:'Aktivität',noSubjects:'Derzeit keine Kurse zugewiesen.',schedule:'Stundenplan',activityRequest:'Antrag'},
    load:{kicker:'Genehmigungsablauf',title:'Mein Lehrangebot',intro:'Senden Sie Ihr Lehrangebot zur Prüfung an die akademische Koordination.',period:'Zeitraum',periodPlaceholder:'Studienzeitraum (z. B. 2026-1)',send:'Zur Prüfung senden',refresh:'Aktualisieren',noLoads:'Noch kein Lehrangebot gesendet.',noPeriod:'Kein Zeitraum',open:'Anmeldungen offen',closed:'Anmeldungen geschlossen',approve:'Genehmigen',reject:'Ablehnen',publish:'Veröffentlichen',sendError:'Lehrangebot konnte nicht gesendet werden.',loadError:'Lehrangebote konnten nicht geladen werden.',updateError:'Lehrangebot konnte nicht aktualisiert werden.'},
    courses:{kicker:'Kurse',mySubjects:'Meine Kurse',key:'Code',schedule:'Stundenplan',back:'Zurück',enrolled:'Eingeschriebene Studierende',name:'Name',user:'Benutzername',program:'Studiengang',selectTitle:'Kursangebot',choose:'Wählen Sie einen Kurs für Ihre Lehre',intro:'Die akademische Koordination pflegt den Katalog. Wählen Sie einen Kurs und tragen Sie Zeit und Raum ein.',professor:'Lehrkraft',available:'Verfügbar',of:'von',students:'Studierende',schedulePlaceholder:'z. B. Montag und Mittwoch 08:00–10:00',room:'Raum',selectRoom:'Raum auswählen',roomOne:'Raum 1 – Kapazität 42',roomLab:'Harold-V.-McIntosh-Labor',meetingRoom:'Besprechungsraum',assignedElsewhere:'Anderer Lehrkraft zugewiesen',updateSchedule:'Stundenplan aktualisieren',selectSubject:'Kurs auswählen',catalogEmpty:'Die akademische Koordination hat noch keine Kurse geladen.',scheduleMissing:'Geben Sie vor der Auswahl einen Stundenplan ein.',roomMissing:'Wählen Sie vor der Zuweisung einen Raum aus.',assignError:'Kurs konnte nicht zugewiesen werden.',connectionError:'Keine Verbindung zum Server.',assignSuccess:'Kurs erfolgreich zugewiesen.'},
    grading:{title:'Noteneintrag',kicker:'NOTEN NACH KURS',intro:'Noten innerhalb der jeweiligen Gruppe erfassen und anzeigen.',partial:'Teilprüfung',number:'Teilprüfungsnummer',final:'Endnote',save:'Note speichern',cancel:'Abbrechen',studentRequired:'Studierende und Note auswählen.',saveError:'Note konnte nicht gespeichert werden.',courseLoad:'Keine Studierenden oder Noten zum Exportieren.',exportHeaders:['Studierende','Benutzername','Kurs','Studiengang','Teilnote 1','Teilnote 2','Teilnote 3','Endnote','Status'],academicStatus:'Akademischer Status',lastUpdate:'Aktualisiert',registration:'Note eintragen',course:'Kurse',export:'Noten exportieren'},
    exams:{title:'Online-Prüfungen',kicker:'Bewertung',student:'Studierende',type:'Prüfungstyp',scheduled:'Geplanter Termin',status:'Status',grade:'Note',attempts:'Versuche',actions:'Aktionen',start:'Starten',finish:'Beenden',gradeAction:'Bewerten',none:'Keine Online-Prüfungen.',startError:'Prüfung konnte nicht gestartet werden.',updateError:'Prüfung konnte nicht aktualisiert werden.',gradePrompt:'Prüfungsnote (0 bis 10):',gradeRange:'Die Note muss zwischen 0 und 10 liegen.',finalGrade:'Endnote'},
    interviews:{title:'Virtuelle Gespräche',kicker:'Kommunikation',closeForm:'Formular schließen',schedule:'Gespräch planen',student:'Studierende',selectStudent:'Studierende auswählen',purpose:'Zweck',purposeOptions:{admision:'Aufnahmegespräch',seguimiento:'Fortschrittsgespräch',tutoria:'Akademische Betreuung',orientacion:'Berufsberatung',otro:'Sonstiges'},titleField:'Titel',date:'Datum und Uhrzeit',duration:'Dauer (Minuten)',description:'Beschreibung / Hinweise',descriptionPlaceholder:'Ziel oder Vorbereitung für die Studierenden angeben.',save:'Planen und Raum erstellen',saving:'Wird gespeichert…',jitsi:'Ein sicherer Jitsi-Raum wird automatisch erstellt.',scheduled:'Geplanter Termin',jitsiCol:'Jitsi',notes:'Notizen',join:'Raum öffnen',available:'Nach Beginn verfügbar',start:'Starten',finish:'Beenden',cancel:'Abbrechen',noActions:'Keine Aktionen',none:'Keine virtuellen Gespräche.',studentDateRequired:'Studierende und Termin für das Gespräch auswählen.',scheduleError:'Gespräch konnte nicht geplant werden.',updateError:'Gespräch konnte nicht aktualisiert werden.',notesPrompt:'Gesprächsnotizen (optional):'},
    requests:{title:'Akademische Anträge',kicker:'Verwaltung',student:'Studierende',type:'Antragstyp',comment:'Kommentar',status:'Status',date:'Datum'},reports:{title:'Allgemeine Statistiken',kicker:'Leistung',analytics:'Akademische Leistung',description:'Kennzahlen zu Gruppen, Prüfungen und Gesprächen der Lehrkraft.',courses:'Kurse',students:'Studierende',exams:'Prüfungen',interviews:'Gespräche',passed:'Bestanden',failed:'Nicht bestanden',completedExams:'Abgeschlossene Prüfungen',completedInterviews:'Abgeschlossene Gespräche',totalStudents:'Studierende insgesamt',unit:'Einheit'},messages:{expired:'Ihre Sitzung ist abgelaufen. Bitte erneut anmelden.',permission:'Sie haben keine Lehrberechtigung für diesen Bereich.',loadError:'Lehrendenbereich konnte nicht geladen werden.',noCatalog:'Kurskatalog konnte nicht geladen werden.',noInterviews:'Gespräch konnte nicht geladen werden.',noExam:'Prüfung konnte nicht geladen werden.',courseError:'Panel konnte nicht geladen werden.'},
  },
  zh:{
    locale:'zh-CN',panel:'教师面板',kicker:'教学',operations:'学术运营',brand:'教师',brandSubtitle:'评估与跟进',logout:'退出登录',refresh:'刷新',loading:'正在加载教师面板...',loadingData:'正在加载数据...',groups:{overview:'概览',teaching:'教学',evaluation:'评估',followup:'跟进'},menu:{overview:'概览',cursos:'我的课程',carga:'我的课程安排',catalogo:'选择课程',estudiantes:'学生',calificaciones:'成绩',examenes:'考试',entrevistas:'会谈',solicitudes:'申请',reportes:'报告',perfil:'我的资料'},
    status:{cursando:'进行中',aprobada:'已通过',reprobada:'未通过',pendiente:'待处理',aceptado:'已接受',rechazado:'已拒绝',programado:'已安排',iniciado:'已开始',completado:'已完成',aprobado:'已通过',cancelado:'已取消',programada:'已安排',iniciada:'已开始',completada:'已完成',cancelada:'已取消'},
    common:{student:'学生',students:'学生',user:'用户名',program:'项目',status:'状态',academicStatus:'学业状态',grade:'成绩',final:'期末',partials:'阶段成绩',course:'课程',credits:'学分',teacher:'教师',schedule:'课表',date:'日期',duration:'时长',minutes:'分钟',pending:'待定',notAssigned:'教师未分配',periodMissing:'未分配学期',update:'刷新',export:'导出',registerGrade:'登记成绩',newGrade:'新成绩',noStudents:'该课程暂无选课学生。',noSubjects:'目前未分配课程。',noRequests:'暂无申请',allResolved:'均已处理',view:'查看',noComment:'暂无备注。',actions:'操作',selectStudent:'选择学生'},
    overview:{courses:'我的课程',assigned:'已分配课程',students:'学生',enrolled:'选课总数',passed:'已通过',recent:'最近活动',exams:'考试',online:'线上考试总数',interviews:'会谈',scheduled:'已安排总数',requests:'申请',toReview:'待审核',courseKicker:'课程',mySubjects:'本学期课程',activity:'活动',noSubjects:'目前未分配课程。',schedule:'课表',activityRequest:'申请'},
    load:{kicker:'审批流程',title:'我的课程安排',intro:'将课程安排提案提交给学术协调部门审核。',period:'学期',periodPlaceholder:'学期（例如 2026-1）',send:'提交审核',refresh:'刷新',noLoads:'尚未提交课程安排。',noPeriod:'无学期',open:'报名开放',closed:'报名关闭',approve:'批准',reject:'拒绝',publish:'发布',sendError:'无法提交课程安排。',loadError:'无法加载课程安排。',updateError:'无法更新课程安排。'},
    courses:{kicker:'课程',mySubjects:'我的课程',key:'代码',schedule:'课表',back:'返回',enrolled:'已选课学生',name:'姓名',user:'用户名',program:'项目',selectTitle:'课程目录',choose:'选择要授课的课程',intro:'学术协调部门维护课程目录。选择可用课程并填写课表和教室。',professor:'教师',available:'可用',of:'/',students:'名学生',schedulePlaceholder:'例如：周一和周三 08:00-10:00',room:'教室',selectRoom:'选择教室',roomOne:'1 号教室 - 最多 42 人',roomLab:'Harold V. McIntosh 实验室',meetingRoom:'会议室',assignedElsewhere:'已分配给其他教师',updateSchedule:'更新课表',selectSubject:'选择课程',catalogEmpty:'学术协调部门尚未上传课程。',scheduleMissing:'选择课程前请填写课表。',roomMissing:'分配课程前请选择教室。',assignError:'无法分配课程。',connectionError:'无法连接服务器。',assignSuccess:'课程分配成功。'},
    grading:{title:'成绩登记',kicker:'按课程登记成绩',intro:'在相应班级中录入和查看成绩。',partial:'阶段成绩',number:'阶段编号',final:'期末成绩',save:'保存成绩',cancel:'取消',studentRequired:'请选择学生并填写成绩。',saveError:'无法登记成绩。',courseLoad:'没有可导出的学生或成绩。',exportHeaders:['学生','用户名','课程','项目','阶段 1','阶段 2','阶段 3','期末','状态'],academicStatus:'学业状态',lastUpdate:'更新时间',registration:'登记成绩',course:'课程',export:'导出成绩'},
    exams:{title:'线上考试',kicker:'评估',student:'学生',type:'考试类型',scheduled:'安排日期',status:'状态',grade:'成绩',attempts:'次数',actions:'操作',start:'开始',finish:'结束',gradeAction:'评分',none:'暂无线上考试。',startError:'无法开始考试。',updateError:'无法更新考试。',gradePrompt:'考试成绩（0 至 10）：',gradeRange:'成绩必须在 0 至 10 之间。',finalGrade:'期末成绩'},
    interviews:{title:'线上会谈',kicker:'沟通',closeForm:'关闭表单',schedule:'安排会谈',student:'学生',selectStudent:'选择学生',purpose:'目的',purposeOptions:{admision:'入学面试',seguimiento:'进度跟进',tutoria:'学业辅导',orientacion:'职业指导',otro:'其他'},titleField:'标题',date:'日期和时间',duration:'时长（分钟）',description:'说明 / 指引',descriptionPlaceholder:'向学生说明会谈目标或准备事项。',save:'安排并生成会议室',saving:'正在保存…',jitsi:'系统将自动生成安全的 Jitsi 会议室。',scheduled:'安排日期',jitsiCol:'Jitsi',notes:'备注',join:'打开会议室',available:'开始后可用',start:'开始',finish:'结束',cancel:'取消',noActions:'无操作',none:'暂无线上会谈。',studentDateRequired:'请选择学生和会谈时间。',scheduleError:'无法安排会谈。',updateError:'无法更新会谈。',notesPrompt:'会谈备注（可选）：'},
    requests:{title:'学术申请',kicker:'管理',student:'学生',type:'申请类型',comment:'备注',status:'状态',date:'日期'},reports:{title:'总体统计',kicker:'表现',analytics:'学业表现',description:'教师负责班级、评估和会谈的指标。',courses:'课程',students:'学生',exams:'考试',interviews:'会谈',passed:'已通过',failed:'未通过',completedExams:'已完成考试',completedInterviews:'已完成会谈',totalStudents:'学生总数',unit:'单位'},messages:{expired:'登录已过期，请重新登录。',permission:'您没有教师面板的访问权限。',loadError:'无法加载教师面板。',noCatalog:'无法加载课程目录。',noInterviews:'无法加载会谈。',noExam:'无法加载考试。',courseError:'无法加载面板。'},
  },
  pt:{
    locale:'pt-BR',panel:'Painel do Docente',kicker:'Ensino',operations:'OPERAÇÃO ACADÊMICA',brand:'Docente',brandSubtitle:'Avaliação e acompanhamento',logout:'Sair',refresh:'Atualizar',loading:'Carregando painel do docente...',loadingData:'Carregando dados...',groups:{overview:'Visão geral',teaching:'Ensino',evaluation:'Avaliação',followup:'Acompanhamento'},menu:{overview:'Resumo',cursos:'Minhas disciplinas',carga:'Minha carga acadêmica',catalogo:'Escolher disciplina',estudiantes:'Alunos',calificaciones:'Notas',examenes:'Provas',entrevistas:'Entrevistas',solicitudes:'Solicitações',reportes:'Relatórios',perfil:'Meu perfil'},
    status:{cursando:'Em andamento',aprobada:'Aprovada',reprobada:'Reprovada',pendiente:'Pendente',aceptado:'Aceito',rechazado:'Rejeitado',programado:'Agendado',iniciado:'Iniciado',completado:'Concluído',aprobado:'Aprovado',cancelado:'Cancelado',programada:'Agendada',iniciada:'Iniciada',completada:'Concluída',cancelada:'Cancelada'},
    common:{student:'Aluno',students:'Alunos',user:'Usuário',program:'Programa',status:'Status',academicStatus:'Situação acadêmica',grade:'Nota',final:'Final',partials:'Parciais',course:'Disciplina',credits:'Créditos',teacher:'Docente',schedule:'Horário',date:'Data',duration:'Duração',minutes:'minutos',pending:'Pendente',notAssigned:'Docente não atribuído',periodMissing:'Sem período atribuído',update:'Atualizar',export:'Exportar',registerGrade:'Registrar nota',newGrade:'Nova nota',noStudents:'Não há alunos inscritos nesta disciplina.',noSubjects:'Nenhuma disciplina atribuída atualmente.',noRequests:'Sem solicitações',allResolved:'Todas resolvidas',view:'Ver',noComment:'Sem comentário.',actions:'Ações',selectStudent:'Selecione um aluno'},
    overview:{courses:'Minhas disciplinas',assigned:'Disciplinas atribuídas',students:'Alunos',enrolled:'Total inscritos',passed:'Aprovados',recent:'Sessões recentes',exams:'Provas',online:'Total on-line',interviews:'Entrevistas',scheduled:'Total agendadas',requests:'Solicitações',toReview:'Pendentes de revisão',courseKicker:'Disciplinas',mySubjects:'Minhas disciplinas neste semestre',activity:'Atividade',noSubjects:'Nenhuma disciplina atribuída atualmente.',schedule:'Horário',activityRequest:'Solicitação'},
    load:{kicker:'Fluxo de aprovação',title:'Minha carga acadêmica',intro:'Envie sua proposta de carga à Coordenação Acadêmica para revisão.',period:'Período',periodPlaceholder:'Período letivo (ex.: 2026-1)',send:'Enviar para revisão',refresh:'Atualizar',noLoads:'Você ainda não enviou uma carga.',noPeriod:'Sem período',open:'Inscrições abertas',closed:'Inscrições encerradas',approve:'Aprovar',reject:'Rejeitar',publish:'Publicar',sendError:'Não foi possível enviar a carga.',loadError:'Não foi possível carregar as cargas.',updateError:'Não foi possível atualizar a carga.'},
    courses:{kicker:'Disciplinas',mySubjects:'Minhas disciplinas',key:'Código',schedule:'Horário',back:'Voltar',enrolled:'Alunos inscritos',name:'Nome',user:'Usuário',program:'Programa',selectTitle:'Oferta acadêmica',choose:'Escolha a disciplina que ministrará',intro:'A Coordenação Acadêmica mantém o catálogo. Selecione uma disciplina disponível e informe horário e sala.',professor:'Docente',available:'Disponível',of:'de',students:'alunos',schedulePlaceholder:'Ex.: segunda e quarta 08:00-10:00',room:'Sala',selectRoom:'Selecione a sala',roomOne:'Sala 1 - capacidade 42',roomLab:'Laboratório Harold V. McIntosh',meetingRoom:'Sala de reuniões',assignedElsewhere:'Atribuída a outro docente',updateSchedule:'Atualizar horário',selectSubject:'Selecionar disciplina',catalogEmpty:'A Coordenação Acadêmica ainda não carregou disciplinas.',scheduleMissing:'Informe o horário antes de selecionar a disciplina.',roomMissing:'Selecione a sala antes de atribuir a disciplina.',assignError:'Não foi possível atribuir a disciplina.',connectionError:'Não foi possível conectar ao servidor.',assignSuccess:'Disciplina atribuída com sucesso.'},
    grading:{title:'Registro de notas',kicker:'NOTAS POR DISCIPLINA',intro:'Registre e consulte as notas dentro da turma correspondente.',partial:'Parcial',number:'Número do parcial',final:'Final',save:'Salvar nota',cancel:'Cancelar',studentRequired:'Selecione um aluno e informe a nota.',saveError:'Não foi possível registrar a nota.',courseLoad:'Não há alunos ou notas para exportar.',exportHeaders:['Aluno','Usuário','Disciplina','Programa','Parcial 1','Parcial 2','Parcial 3','Final','Status'],academicStatus:'Situação acadêmica',lastUpdate:'Atualização',registration:'Registrar nota',course:'Disciplinas',export:'Exportar notas'},
    exams:{title:'Provas on-line',kicker:'Avaliação',student:'Aluno',type:'Tipo de prova',scheduled:'Data agendada',status:'Status',grade:'Nota',attempts:'Tentativas',actions:'Ações',start:'Iniciar',finish:'Finalizar',gradeAction:'Avaliar',none:'Não há provas on-line.',startError:'Não foi possível iniciar a prova.',updateError:'Não foi possível atualizar a prova.',gradePrompt:'Nota da prova (0 a 10):',gradeRange:'A nota deve ser um número entre 0 e 10.',finalGrade:'Nota final'},
    interviews:{title:'Entrevistas virtuais',kicker:'Comunicação',closeForm:'Fechar formulário',schedule:'Agendar entrevista',student:'Aluno',selectStudent:'Selecione um aluno',purpose:'Finalidade',purposeOptions:{admision:'Entrevista de admissão',seguimiento:'Acompanhamento de progresso',tutoria:'Tutoria acadêmica',orientacion:'Orientação profissional',otro:'Outro'},titleField:'Título',date:'Data e hora',duration:'Duração (minutos)',description:'Descrição / instruções',descriptionPlaceholder:'Informe ao aluno o objetivo ou preparação necessária.',save:'Agendar e gerar sala',saving:'Salvando…',jitsi:'Uma sala segura do Jitsi é gerada automaticamente.',scheduled:'Data agendada',jitsiCol:'Jitsi',notes:'Notas',join:'Abrir sala',available:'Disponível ao iniciar',start:'Iniciar',finish:'Finalizar',cancel:'Cancelar',noActions:'Sem ações',none:'Não há entrevistas virtuais.',studentDateRequired:'Selecione um aluno e uma data para agendar a entrevista.',scheduleError:'Não foi possível agendar a entrevista.',updateError:'Não foi possível atualizar a entrevista.',notesPrompt:'Notas da entrevista (opcional):'},
    requests:{title:'Solicitações acadêmicas',kicker:'Gestão',student:'Aluno',type:'Tipo de solicitação',comment:'Comentário',status:'Status',date:'Data'},reports:{title:'Estatísticas gerais',kicker:'Desempenho',analytics:'Desempenho acadêmico',description:'Indicadores de turmas, avaliações e entrevistas sob responsabilidade do docente.',courses:'Disciplinas',students:'Alunos',exams:'Provas',interviews:'Entrevistas',passed:'Aprovados',failed:'Reprovados',completedExams:'Provas concluídas',completedInterviews:'Entrevistas concluídas',totalStudents:'Total de alunos',unit:'Unidade'},messages:{expired:'Sua sessão expirou. Entre novamente.',permission:'Você não tem permissão de docente para acessar este painel.',loadError:'Não foi possível carregar o painel do docente.',noCatalog:'Não foi possível carregar o catálogo.',noInterviews:'Não foi possível carregar a entrevista.',noExam:'Não foi possível carregar a prova.',courseError:'Não foi possível carregar o painel.'},
  },
};

export function useTeacherCopy() {
  const {language} = useLanguage();
  return catalog[language] || catalog.es;
}