# Generated by Django 5.0.6 on 2026-08-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aspirante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('usuario', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=180)),
                ('curp', models.CharField(max_length=18, unique=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('nacimiento', models.DateField(blank=True, null=True)),
                ('estado_actual', models.CharField(max_length=80)),
                ('municipio_actual', models.CharField(max_length=80)),
                ('direccion_actual', models.CharField(max_length=255)),
                ('estado_permanente', models.CharField(max_length=80)),
                ('municipio_permanente', models.CharField(max_length=80)),
                ('direccion_permanente', models.CharField(max_length=255)),
                ('nombre_familiar', models.CharField(max_length=180)),
                ('parentesco', models.CharField(max_length=60)),
                ('telefono_familiar', models.CharField(max_length=20)),
                ('ultimo_grado', models.CharField(max_length=80)),
                ('institucion', models.CharField(max_length=180)),
                ('promedio', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('idiomas', models.TextField(blank=True)),
                ('publicaciones', models.TextField(blank=True)),
                ('apoyos', models.TextField(blank=True)),
                ('experiencia', models.TextField(blank=True)),
                ('unidad', models.CharField(max_length=120)),
                ('departamento', models.CharField(max_length=120)),
                ('seccion', models.CharField(max_length=120)),
                ('programa', models.CharField(max_length=180)),
                ('modalidad', models.CharField(choices=[('Presencial', 'Presencial'), ('Híbrida', 'Híbrida'), ('En línea', 'En línea')], default='Presencial', max_length=20)),
                ('tutor_propuesto', models.CharField(blank=True, max_length=180)),
                ('comentarios', models.TextField(blank=True)),
                ('business_key', models.CharField(blank=True, max_length=120, unique=True)),
                ('proceso_estado', models.CharField(default='pendiente', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Aspirante',
                'verbose_name_plural': 'Aspirantes',
            },
        ),
    ]
