# Generated by Django 5.0.6 on 2026-08-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preregistro', '0003_seguimiento_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirante',
            name='rol',
            field=models.CharField(choices=[('aspirante', 'Aspirante'), ('docente', 'Docente')], default='aspirante', max_length=20),
        ),
    ]
