# Generated by Django 5.0.6 on 2026-08-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preregistro', '0004_aspirante_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspirante',
            name='rol',
            field=models.CharField(choices=[('aspirante', 'Aspirante'), ('alumno', 'Alumno'), ('docente', 'Docente')], default='aspirante', max_length=20),
        ),
    ]
