# Generated by Django 5.0.6 on 2026-08-17 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preregistro', '0009_create_materia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='ExamenEnLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('admision', 'Examen de Admisión'), ('seleccion', 'Examen de Selección'), ('diagnostico', 'Examen de Diagnóstico'), ('otro', 'Otro')], max_length=20)),
                ('titulo', models.CharField(default='Examen en línea', max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('business_key', models.CharField(blank=True, max_length=120, unique=True)),
                ('camunda_instance_id', models.CharField(blank=True, max_length=80)),
                ('fecha_programada', models.DateTimeField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('duracion_minutos', models.PositiveIntegerField(default=90)),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('iniciado', 'Iniciado'), ('completado', 'Completado'), ('aprobado', 'Aprobado'), ('reprobado', 'Reprobado'), ('cancelado', 'Cancelado')], default='programado', max_length=20)),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('intentos', models.PositiveIntegerField(default=0)),
                ('max_intentos', models.PositiveIntegerField(default=3)),
                ('retroalimentacion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aspirante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes_en_linea', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Examen en línea',
                'verbose_name_plural': 'Exámenes en línea',
                'ordering': ['-fecha_programada'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('historial', 'Historial académico'), ('reinscripcion', 'Reinscripción'), ('ajuste_materias', 'Ajuste de materias')], max_length=40)),
                ('comentario', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aspirante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_academicas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud académica',
                'verbose_name_plural': 'Solicitudes académicas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('cursando', 'Cursando'), ('aprobada', 'Aprobada'), ('reprobada', 'Reprobada')], default='cursando', max_length=20)),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('horario', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aspirante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to=settings.AUTH_USER_MODEL)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='preregistro.materia')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'unique_together': {('aspirante', 'materia')},
            },
        ),
    ]
