# Generated by Django 5.0.6 on 2026-08-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preregistro', '0010_alter_materia_id_examenenlinea_solicitudacademica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirante',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/%Y/%m/'),
        ),
    ]
