# Generated by Django 5.0.6 on 2026-09-17 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preregistro', '0030_configuracionprograma_planestudiomateria_solicituddirecciontesis'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisionAntiplagio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(choices=[('turnitin', 'Turnitin'), ('copyleaks', 'Copyleaks'), ('manual', 'Manual institucional')], default='turnitin', max_length=30)),
                ('archivo', models.FileField(upload_to='antiplagio/%Y/%m/')),
                ('nombre_original', models.CharField(max_length=255)),
                ('porcentaje_similitud', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En revisión'), ('aprobado', 'Aprobado'), ('observado', 'Observado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('resultados', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisiones_antiplagio', to='preregistro.proyectotesis')),
            ],
            options={
                'verbose_name': 'Revisión anti-plagio',
                'verbose_name_plural': 'Revisiones anti-plagio',
                'ordering': ['-created_at'],
            },
        ),
    ]
