# Generated by Django 5.0.6 on 2026-09-17 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preregistro', '0031_revisionantiplagio'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefensaTesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('lugar', models.CharField(blank=True, max_length=200)),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual'), ('hibrida', 'Híbrida')], default='presencial', max_length=20)),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada'), ('revisada', 'Revisada')], default='programada', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('calificacion_final', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('acta_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proyecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='defensa_tesis', to='preregistro.proyectotesis')),
            ],
            options={
                'verbose_name': 'Defensa de tesis',
                'verbose_name_plural': 'Defensas de tesis',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='JuradoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('presidente', 'Presidente'), ('secretario', 'Secretario'), ('vocal', 'Vocal'), ('suplente', 'Suplente')], default='vocal', max_length=20)),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jurado', models.ForeignKey(limit_choices_to={'rol': 'docente'}, on_delete=django.db.models.deletion.CASCADE, related_name='jurados_asignados', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jurados', to='preregistro.proyectotesis')),
            ],
            options={
                'ordering': ['orden', 'rol'],
            },
        ),
        migrations.AddConstraint(
            model_name='juradoproyecto',
            constraint=models.UniqueConstraint(fields=('proyecto', 'jurado'), name='jurado_unico_por_proyecto'),
        ),
        migrations.AddConstraint(
            model_name='juradoproyecto',
            constraint=models.UniqueConstraint(condition=models.Q(('rol__in', ['presidente', 'secretario', 'vocal', 'suplente'])), fields=('proyecto', 'rol'), name='rol_unico_por_proyecto'),
        ),
    ]
