# Generated by Django 5.0.6 on 2026-09-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preregistro', '0032_defensatesis_juradoproyecto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='defensatesis',
            name='enlace_virtual',
            field=models.URLField(blank=True),
        ),
    ]
