# Generated by Django 5.0.6 on 2026-09-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preregistro', '0033_defensatesis_enlace_virtual'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='capacidad',
            field=models.PositiveSmallIntegerField(default=42),
        ),
        migrations.AddField(
            model_name='materia',
            name='salon',
            field=models.CharField(choices=[('salon_1', 'Salón 1'), ('laboratorio_harold', 'Laboratorio Harold V. McIntosh'), ('sala_juntas', 'Sala de Juntas')], default='salon_1', max_length=40),
        ),
    ]
